<a href="https://colab.research.google.com/github/rahulg202/machine_learning/blob/main/machine_learning_da.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df=pd.read_csv('/content/polynomial_regression_data.csv')
df.head()

Year  Hard Disc Capacity (TB)  Processor Speed (GHz)  \
0  2016                      6.0                    2.1   
1  2013                      3.5                    2.9   
2  2022                      2.0                    4.9   
3  2024                      4.5                    2.3   
4  2020                      1.5                    3.3   

   Price of Computer (USD)  
0                   6198.7  
1                   4786.2  
2                   5730.7  
3                   5007.8  
4                   3659.8

In [ ]:
x=df.iloc[:,0:3]
x

Year  Hard Disc Capacity (TB)  Processor Speed (GHz)
0   2016                      6.0                    2.1
1   2013                      3.5                    2.9
2   2022                      2.0                    4.9
3   2024                      4.5                    2.3
4   2020                      1.5                    3.3
5   2017                      2.5                    3.5
6   2022                      1.5                    3.4
7   2014                      3.5                    2.7
8   2016                      2.5                    3.3
9   2019                      4.5                    4.2
10  2012                      3.5                    4.7
11  2016                      1.0                    4.4
12  2020                      2.0                    4.9
13  2020                      4.5                    2.7
14  2017                      6.0                    4.0
15  2014                      7.0                    3.5
16  2013                      1.0                    3.2
17  2017                      5.0                    3.7
18  2017                      4.5                    3.4
19  2012                      5.0                    4.0
20  2015                      2.5                    4.3
21  2014                      1.0                    4.5
22  2011                      2.0                    4.4
23  2017                      6.0                    4.7
24  2021                      7.5                    4.7
25  2023                      6.0                    4.7
26  2015                      3.5                    3.2
27  2011                      6.0                    2.8
28  2021                      6.5                    4.8
29  2014                      4.0                    3.4
30  2010                      7.5                    3.2
31  2021                      1.5                    2.0
32  2019                      7.0                    4.4
33  2015                      0.5                    2.6
34  2022                      2.0                    2.8
35  2021                      1.0                    4.3
36  2018                      4.0                    2.0
37  2010                      2.0                    3.1
38  2020                      1.0                    2.7
39  2020                      7.0                    4.3
40  2024                      3.0                    3.0
41  2019                      3.0                    3.8
42  2021                      5.0                    3.6
43  2021                      2.0                    2.7
44  2024                      3.0                    2.2
45  2023                      6.5                    2.2
46  2023                      7.5                    2.0
47  2024                      1.0                    4.6
48  2023                      5.0                    2.4
49  2012                      6.0                    2.9

In [ ]:
y=df.iloc[:,-1]
y

0      6198.7
1      4786.2
2      5730.7
3      5007.8
4      3659.8
5      4595.0
6      3751.7
7      4577.8
8      4389.8
9      7297.3
10     6913.8
11     4365.2
12     5730.7
13     5447.8
14     8720.0
15     9207.5
16     3246.8
17     7168.3
18     6271.7
19     7570.0
20     5471.8
21     4467.5
22     5155.2
23     9776.3
24    11793.8
25     9776.3
26     5109.3
27     7068.8
28    10585.3
29     5789.2
30     9389.3
31     2592.5
32    10605.2
33     2495.7
34     3548.8
35     4264.3
36     4280.0
37     3822.7
38     2840.3
39    10444.3
40     4480.0
41     5340.8
42     7037.2
43     3460.3
44     3708.8
45     6841.3
46     7692.5
47     4571.2
48     5573.2
49     7198.7
Name: Price of Computer (USD), dtype: float64

In [ ]:
x=np.array(x)
y=np.array(y).reshape(len(y),1)
print(x.shape,y.shape)

(50, 3) (50, 1)


In [ ]:
#normlization

scaler_linear= StandardScaler()
X_n= scaler_linear.fit_transform(x)
X_n


array([[-0.44848061,  1.02114249, -1.53700492],
       [-1.17183643, -0.16073539, -0.63817163],
       [ 0.99823103, -0.86986212,  1.60891158],
       [ 1.48046825,  0.31201576, -1.3122966 ],
       [ 0.51599382, -1.1062377 , -0.18875499],
       [-0.207362  , -0.63348655,  0.03595333],
       [ 0.99823103, -1.1062377 , -0.07640083],
       [-0.93071782, -0.16073539, -0.86287995],
       [-0.44848061, -0.63348655, -0.18875499],
       [ 0.27487521,  0.31201576,  0.82243246],
       [-1.41295504, -0.16073539,  1.38420326],
       [-0.44848061, -1.34261327,  1.04714078],
       [ 0.51599382, -0.86986212,  1.60891158],
       [ 0.51599382,  0.31201576, -0.86287995],
       [-0.207362  ,  1.02114249,  0.59772413],
       [-0.93071782,  1.49389364,  0.03595333],
       [-1.17183643, -1.34261327, -0.30110915],
       [-0.207362  ,  0.54839134,  0.26066165],
       [-0.207362  ,  0.31201576, -0.07640083],
       [-1.41295504,  0.54839134,  0.59772413],
       [-0.68959922, -0.63348655,  0.934

In [ ]:
X_train,X_test,Y_train,Y_test= train_test_split(X_n,y,test_size=0.4,random_state=1)
X_test,X_val,Y_test,Y_val= train_test_split(X_test,Y_test,test_size=0.5,random_state=1)

print('shape of training set:',X_train.shape,Y_train.shape)
print('shape of validation set:',X_val.shape,Y_val.shape)
print('shape of test set:',X_test.shape,Y_test.shape)

shape of training set: (30, 3) (30, 1)
shape of validation set: (10, 3) (10, 1)
shape of test set: (10, 3) (10, 1)


In [ ]:
linear_model= LinearRegression()
linear_model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
#error on train data
yhat=linear_model.predict(X_train)
print(mean_squared_error(Y_train,yhat)/2)

36724.62761742722


In [ ]:
#error on validation data
yhat_val=linear_model.predict(X_val)
print(mean_squared_error(Y_val,yhat_val)/2)

40551.4647930713


In [ ]:
#error on test data
yhat_test=linear_model.predict(X_test)
print(mean_squared_error(Y_test,yhat_test)/2)

41756.24863457809


**Polynomial Regression**

In [ ]:
X_train,X_test,Y_train,Y_test= train_test_split(x,y,test_size=0.4,random_state=1)
X_test,X_val,Y_test,Y_val= train_test_split(X_test,Y_test,test_size=0.5,random_state=1)

print('shape of training set:',X_train.shape,Y_train.shape)
print('shape of validation set:',X_val.shape,Y_val.shape)
print('shape of test set:',X_test.shape,Y_test.shape)

shape of training set: (30, 3) (30, 1)
shape of validation set: (10, 3) (10, 1)
shape of test set: (10, 3) (10, 1)


In [ ]:
train_mses=[]
polys=[]
scalers=[]
models=[]
train_mses=[]
val_mses=[]

for degree in range(1,11):

  poly= PolynomialFeatures(degree,include_bias=False)
  X_train_mapped=poly.fit_transform(X_train)
  polys.append(poly)

  Scaler_poly=StandardScaler()
  X_train_mapped_scaled= Scaler_poly.fit_transform(X_train_mapped)
  scalers.append(Scaler_poly)

  model= LinearRegression()
  model.fit(X_train_mapped_scaled,Y_train)

  models.append(model)

  yhat=model.predict(X_train_mapped_scaled)
  mse_train= mean_squared_error(Y_train,yhat)/2
  train_mses.append(mse_train)

  X_val_mapped=poly.transform(X_val)
  X_val_mapped_scaled=Scaler_poly.transform(X_val_mapped)

  yhat_val=model.predict(X_val_mapped_scaled)
  mse_val=mean_squared_error(Y_val,yhat_val)/2
  val_mses.append(mse_val)s

In [ ]:
#selecting the best model
print(val_mses)
degree= np.argmin(val_mses)+1
degree

[40551.46479307133, 2.491881595315996e-24, 4.011825970882184e-24, 1.872932340764628e-07, 0.005381546290877946, 0.008834196405629, 0.02527767693097414, 0.06157521728343943, 0.13067291140674922, 0.25547700908006127]


2

In [ ]:
X_test_mapped= polys[degree-1].transform(X_test)
X_test_mapped_scaled= scalers[degree-1].transform(X_test_mapped)

yhat= models[degree-1].predict(X_test_mapped_scaled)
print(train_mses[degree-1])
print(val_mses[degree-1])
print(mean_squared_error(Y_test,yhat)/2)

2.7951811532521062e-24
2.491881595315996e-24
4.228960881677354e-24


# **Logistic Regression**

In [ ]:
# Load your data
dff = pd.read_csv('/content/polynomial_regression_data.csv')

# Rename columns
dff.columns = ['Year', 'Hard_Disc_Capacity_TB', 'Processor_Speed_GHz', 'Price_of_Computer_USD']

dff.head()


Year  Hard_Disc_Capacity_TB  Processor_Speed_GHz  Price_of_Computer_USD
0  2016                    6.0                  2.1                 6198.7
1  2013                    3.5                  2.9                 4786.2
2  2022                    2.0                  4.9                 5730.7
3  2024                    4.5                  2.3                 5007.8
4  2020                    1.5                  3.3                 3659.8

In [ ]:
bins = [0, 5000, 8000, float('inf')]
labels = ['low', 'medium', 'high']

dff['budget'] = pd.cut(dff['Price_of_Computer_USD'], bins=bins, labels=labels, right=False)

dff.head()

Year  Hard_Disc_Capacity_TB  Processor_Speed_GHz  Price_of_Computer_USD  \
0  2016                    6.0                  2.1                 6198.7   
1  2013                    3.5                  2.9                 4786.2   
2  2022                    2.0                  4.9                 5730.7   
3  2024                    4.5                  2.3                 5007.8   
4  2020                    1.5                  3.3                 3659.8   

   budget  
0  medium  
1     low  
2  medium  
3  medium  
4     low

In [ ]:
dff['budget_encoded'] = dff['budget'].map({'low': 0, 'medium': 1, 'high': 2})
dff.head()

Year  Hard_Disc_Capacity_TB  Processor_Speed_GHz  Price_of_Computer_USD  \
0  2016                    6.0                  2.1                 6198.7   
1  2013                    3.5                  2.9                 4786.2   
2  2022                    2.0                  4.9                 5730.7   
3  2024                    4.5                  2.3                 5007.8   
4  2020                    1.5                  3.3                 3659.8   

   budget budget_encoded  
0  medium              1  
1     low              0  
2  medium              1  
3  medium              1  
4     low              0

In [ ]:
X = dff.iloc[:, :-2]
np.array(X)


Year  Hard_Disc_Capacity_TB  Processor_Speed_GHz  Price_of_Computer_USD
0   2016                    6.0                  2.1                 6198.7
1   2013                    3.5                  2.9                 4786.2
2   2022                    2.0                  4.9                 5730.7
3   2024                    4.5                  2.3                 5007.8
4   2020                    1.5                  3.3                 3659.8
5   2017                    2.5                  3.5                 4595.0
6   2022                    1.5                  3.4                 3751.7
7   2014                    3.5                  2.7                 4577.8
8   2016                    2.5                  3.3                 4389.8
9   2019                    4.5                  4.2                 7297.3
10  2012                    3.5                  4.7                 6913.8
11  2016                    1.0                  4.4                 4365.2
12  2020                    2.0                  4.9                 5730.7
13  2020                    4.5                  2.7                 5447.8
14  2017                    6.0                  4.0                 8720.0
15  2014                    7.0                  3.5                 9207.5
16  2013                    1.0                  3.2                 3246.8
17  2017                    5.0                  3.7                 7168.3
18  2017                    4.5                  3.4                 6271.7
19  2012                    5.0                  4.0                 7570.0
20  2015                    2.5                  4.3                 5471.8
21  2014                    1.0                  4.5                 4467.5
22  2011                    2.0                  4.4                 5155.2
23  2017                    6.0                  4.7                 9776.3
24  2021                    7.5                  4.7                11793.8
25  2023                    6.0                  4.7                 9776.3
26  2015                    3.5                  3.2                 5109.3
27  2011                    6.0                  2.8                 7068.8
28  2021                    6.5                  4.8                10585.3
29  2014                    4.0                  3.4                 5789.2
30  2010                    7.5                  3.2                 9389.3
31  2021                    1.5                  2.0                 2592.5
32  2019                    7.0                  4.4                10605.2
33  2015                    0.5                  2.6                 2495.7
34  2022                    2.0                  2.8                 3548.8
35  2021                    1.0                  4.3                 4264.3
36  2018                    4.0                  2.0                 4280.0
37  2010                    2.0                  3.1                 3822.7
38  2020                    1.0                  2.7                 2840.3
39  2020                    7.0                  4.3                10444.3
40  2024                    3.0                  3.0                 4480.0
41  2019                    3.0                  3.8                 5340.8
42  2021                    5.0                  3.6                 7037.2
43  2021                    2.0                  2.7                 3460.3
44  2024                    3.0                  2.2                 3708.8
45  2023                    6.5                  2.2                 6841.3
46  2023                    7.5                  2.0                 7692.5
47  2024                    1.0                  4.6                 4571.2
48  2023                    5.0                  2.4                 5573.2
49  2012                    6.0                  2.9                 7198.7

In [ ]:
y = dff['budget_encoded']
y

0     1
1     0
2     1
3     1
4     0
5     0
6     0
7     0
8     0
9     1
10    1
11    0
12    1
13    1
14    2
15    2
16    0
17    1
18    1
19    1
20    1
21    0
22    1
23    2
24    2
25    2
26    1
27    1
28    2
29    1
30    2
31    0
32    2
33    0
34    0
35    0
36    0
37    0
38    0
39    2
40    0
41    1
42    1
43    0
44    0
45    1
46    1
47    0
48    1
49    1
Name: budget_encoded, dtype: category
Categories (3, int64): [0 < 1 < 2]

In [ ]:
x=np.array(X)
y=np.array(y).reshape(len(y),1)
print(x.shape,y.shape)

(50, 4) (50, 1)


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.4, random_state=1)
X_test, X_val, Y_test, Y_val = train_test_split(X_test, Y_test, test_size=0.5, random_state=1)

print('shape of training set:',X_train.shape,Y_train.shape)
print('shape of validation set:',X_val.shape,Y_val.shape)
print('shape of test set:',X_test.shape,Y_test.shape)

shape of training set: (30, 4) (30, 1)
shape of validation set: (10, 4) (10, 1)
shape of test set: (10, 4) (10, 1)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, roc_auc_score

logistic_model = LogisticRegression(multi_class='ovr', max_iter=1000)
logistic_model.fit(X_train, Y_train.ravel())

Y_pred = logistic_model.predict(X_train)
Y_prob = logistic_model.predict_proba(X_train)

conf_matrix = confusion_matrix(Y_train, Y_pred)
accuracy = accuracy_score(Y_train, Y_pred)
recall = recall_score(Y_train, Y_pred, average='weighted')
precision = precision_score(Y_train, Y_pred, average='weighted')

roc_auc = roc_auc_score(Y_train, Y_prob, multi_class='ovr')

print('Confusion Matrix:\n', conf_matrix)
print('Accuracy:', accuracy)
print('Recall:', recall)
print('Precision:', precision)
print('ROC AUC:', roc_auc)


Confusion Matrix:
 [[14  0  0]
 [ 0  9  0]
 [ 0  0  7]]
Accuracy: 1.0
Recall: 1.0
Precision: 1.0
ROC AUC: 1.0


In [ ]:
Y_pred = logistic_model.predict(X_test)
Y_prob = logistic_model.predict_proba(X_test)

conf_matrix = confusion_matrix(Y_test, Y_pred)
accuracy = accuracy_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred, average='weighted')
precision = precision_score(Y_test, Y_pred, average='weighted')

roc_auc = roc_auc_score(Y_test, Y_prob, multi_class='ovr')

print('Confusion Matrix:\n', conf_matrix)
print('Accuracy:', accuracy)
print('Recall:', recall)
print('Precision:', precision)
print('ROC AUC:', roc_auc)


Confusion Matrix:
 [[3 0 0]
 [1 5 0]
 [0 0 1]]
Accuracy: 0.9
Recall: 0.9
Precision: 0.925
ROC AUC: 1.0


In [ ]:
Y_pred = logistic_model.predict(X_val)
Y_prob = logistic_model.predict_proba(X_val)

conf_matrix = confusion_matrix(Y_val, Y_pred)
accuracy = accuracy_score(Y_val, Y_pred)
recall = recall_score(Y_val, Y_pred, average='weighted')
precision = precision_score(Y_val, Y_pred, average='weighted')

roc_auc = roc_auc_score(Y_val, Y_prob, multi_class='ovr')

print('Confusion Matrix:\n', conf_matrix)
print('Accuracy:', accuracy)
print('Recall:', recall)
print('Precision:', precision)
print('ROC AUC:', roc_auc)


Confusion Matrix:
 [[3 0 0]
 [0 6 0]
 [0 0 1]]
Accuracy: 1.0
Recall: 1.0
Precision: 1.0
ROC AUC: 1.0
